### ISSUE TITLE
record video of me or people talking about the event so people can watch it

### ISSUE THREAD

**Issue by silky** [OpenScienceWorkshops/OpenScienceWorkshops.github.io#48]
and be excited

**Comment by silky** [comment]
here's a video - https://vimeo.com/97493014

i don't know. maybe i should record it again with a script ...

did i miss anything obvious?

**Comment by silky** [comment]
i.e. "what/why/where". i forgot to say where to go for more information, i think it was silly to say we'd say more about open science on the day, and perhaps it seems too focused on programming. oh well.

**Comment by andreabedini** [comment]
lol, you're awesome

**Comment by fhk** [comment]
nice! Also people may not even know what version control is :-) maybe a
closing bye would be nice to "See you there..."

On Fri, Jun 6, 2014 at 2:16 PM, Andrea Bedini notifications@github.com
wrote:

> lol, you're awesome
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenScienceWorkshops/OpenScienceWorkshops.github.io/issues/48#issuecomment-45301492
> .

## 

*Fabion Kauker                 *

_Optimisation Consultant_
_Biarri Networks_
M +61 412 840 802
E fabion.kauker@biarri.com
W www.biarrinetworks.com
A 180 Albert St
  Windsor VIC
  Australia 3181

*Biarri has been selected as one of the world's best analytics teams and is
one of six finalists for the prestigious 2014 INFORMS Franz Edelman Prize. *
http://bit.ly/JK1bQJ

**Comment by silky** [comment]
yeah, i realise i forgot to say goodbye, or really tell them any more detail. i could go record that now and add it on maybe

yeah, i could also have explained version control. hmm.

**Comment by silky** [comment]
alright, i've updated the video - https://vimeo.com/97493014

the editing ... could be better. but perhaps it's at least acceptable ... will put it on the website later unless there are some concerns that it will make people not want to attend ...
