### ISSUE TITLE
Contact info...? And Permissions

### ISSUE THREAD

**Issue by AMChalkie** [OpenScienceWorkshops/OpenScienceWorkshops.github.io#55]
I was looking for an email on the site and never found one. This is because I want to bring attention to the fact that many researchers do not have administrator rights to install software on their machines. In such cases a list of software that would be being installed may help. (I'm guessing git, iPython - right?)

**Comment by silky** [comment]
Hi! Thanks for a reporting an issue with the website! Awesome!

Also, great suggestion! I will add a list of software that we want to install! (It'll just be git; ipython won't need to be run locally at all!)

**Comment by andreabedini** [comment]
Also I became quite good at installing things in user space. I can add some notes.

**Comment by silky** [comment]
i've added a note about permissions; won't bother with listing the software; at least not at this point.
