### ISSUE TITLE
think of backup plan if SMC isn't available

### ISSUE THREAD

**Issue by silky** [OpenScienceWorkshops/OpenScienceWorkshops.github.io#58]
andrew suggests perhaps - https://github.com/UnataInc/ipydra

i think i might also just email william stein, and see what he thinks. i know google drive also supports ipython notebook collaboration, apparently.

**Comment by andreabedini** [comment]
I didn't know of ipydra, great catch. We should get this running on the Nectar cloud directly (every researcher in AU has already access to it). And I need to finish to iPython cloud notebook store.

**Comment by silky** [comment]
i've emailed wstein, yet to hear back

yes, nice idea about nectar ... also, the cloud store thing sounds cool!

**Comment by silky** [comment]
clare slogget has contacted me; she apparently is related to nectar in some way; so we can fall back onto there if SMC doesn't work.

i'd prefer to talk about SMC because it's free and global; not restricted to australian researchers only. i also suspect it does more.
