### ISSUE TITLE
provide a bit more information about what will actually happen on the day

### ISSUE THREAD

**Issue by silky** [OpenScienceWorkshops/OpenScienceWorkshops.github.io#59]
i think some people are confused; probably rightly so.

**Comment by Ivoz** [comment]
I'd love to help out with this, but relating to this issue I don't know what direction to go in order to. Pull Request what?

**Comment by silky** [comment]
Hey @Ivoz! Yes, my bad, this task isn't particularly clear.

What I was wanting to do was expand more on the information I put over here - https://github.com/OpenScienceWorkshops/osw-material/wiki/Agenda-for-1-day-workshop - and put it on the website.

i think i'll probably do this for now.

are you interested in coming along on the day to help out? if so, just email me and i'll forward you the information for volunteers! sorry it's taken me so long to respond to this!

**Comment by silky** [comment]
i'm claiming this is now done with the addition of the calendar.
