### ISSUE TITLE
convert osw into "open science unconference" perhaps?

### ISSUE THREAD

**Issue by silky** [OpenScienceWorkshops/OpenScienceWorkshops.github.io#75]
in light of software carpentry, maybe we can form more of an unconference.

it could have two tracks still, but maybe make the teaching track slightly smaller, and just ask software carpentry to do that, if they want.

alongside that, we could just have people come along and talk about stuff. it could run twice a year.

**Comment by silky** [comment]
nope

**Comment by redacted** [comment]
Given the really good volunteer/attendee ratio, maybe something pair-programming based? Take people from a raw text file through analysis to plotting figures (or, depending on "track" from zero to loading raw text...)

**Comment by silky** [comment]
@redacted thing is, i think at least that sort of thing is definitely the goal of the software carpentry group - http://software-carpentry.org/bootcamps/ - even if i personally find the name a bit odd. so i think my view at the moment is that it's best to leave it to them, or at least direct people to them if they want that sort of thing.

i note this exists - http://offtopicarium.wikidot.com/ - this is something i'd love to be involved with.

**Comment by redacted** [comment]
Fair enough, no need to step on toes!
