### ISSUE TITLE
host another one in late 2015; maybe october?

### ISSUE THREAD

**Issue by silky** [OpenScienceWorkshops/OpenScienceWorkshops.github.io#80]
will need to:
- [ ] secure venue
- [ ] get money again
- [ ] decide on new content

**Comment by silky** [comment]
if we do this, i want to follow much more lyndon/andys style for the haskell workshop https://github.com/sordina/haskell_workshop

**Comment by silky** [comment]
and read over this - https://github.com/OpenScienceWorkshops/osw-material/wiki/Summary-of-the-July-2014-Melbourne-Open-Science-Workshop

**Comment by andreabedini** [comment]
@cryptarch and I were thinking of organising something for maths&stats later in the year.

**Comment by silky** [comment]
ah cool; that's a good idea!

**Comment by silky** [comment]
any further thoughts on this?

**Comment by andreabedini** [comment]
@silky sorry, I haven't really had the time to think about this

**Comment by silky** [comment]
@andykitchen @sauramaia ?

i guess i only want to run it again if there's something quite new and interesting to talk about. i can't think of anything, at the moment.

**Comment by cryptarch** [comment]
I'd potentially be interested. I'm meant to be giving a LaTeX workshop for ResBaz at some point, which could possibly be done as part of an Open Science workshop. I could also do another run of my "Tim's War on Git" talk that I gave to MLUG, which involved looking at how Git works under the hood.

**Comment by silky** [comment]
after thinking about this a reasonable amount, i can't get motivated enough to do it, so it's a "no" for me. closing.

**Comment by sauramaia** [comment]
we may be organising something like the pre-govhack training sessions
leading up to healthhack. merely a rumour at this stage. in which case,
would you care to be involved?

**Comment by silky** [comment]
yeah sure, i'd definitely be happy to help out!
